//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YEMEKCI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int ID { get; set; }
        public int cartID { get; set; }
        public int dishID { get; set; }
        public int quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Dish Dish { get; set; }
    }
}
